language: php

php:
- 7.1
- 7.2

services:
  sqlite:
    adapter: sqlite3
    database: ":memory:"
    timeout: 500

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
  - $HOME/.composer/cache

before_script:
- cp .env.travis .env
- travis_retry composer self-update
- travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
- vendor/bin/phpunit -c phpunit.xml

