pkgname  = "model"
output   = "app/domain/model"
wipe     = true
no-tests = true

[mysql]
  dbname  = "spiderx"
  host    = "127.0.0.1"
  port    = 3306
  user    = "root"
  pass    = "123456"
  sslmode = "false"