CREATE TABLE `torrents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `info_hash` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` int(10) unsigned NOT NULL DEFAULT '0',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `simple_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment_count` int(10) unsigned NOT NULL DEFAULT '0',
  `view_count` int(10) unsigned NOT NULL DEFAULT '0',
  `seeder_count` int(10) unsigned NOT NULL DEFAULT '0',
  `leecher_count` int(10) unsigned NOT NULL DEFAULT '0',
  `snatcher_count` int(10) unsigned NOT NULL DEFAULT '0',
  `reward_bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `is_anonymous` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `position_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `uploader_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发布者ID',
  `owner_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '所有者ID',
  `state` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0: 等待发布 1: 正常种子 2: 断种',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `idx_u_info_hash` (`info_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;